openapi: "3.0.0"
info:
  title: Pendulum API
  version: 0.0.1
servers:
  - url: https://dev.sample-server.com/v1
    description: Production Server
paths:
  /numbered_ticket:
    get:
      tags:
        - Matchings
      summary: create a waiting user
      responses:
        '200':
          description: a uuid that is used in matching list
          content:
            application/json:
              schema: 
                type: string
                example:
                  numberedTicket: 550e8400e29b41d4a716446655440000
  /waiting_users/{numberedTicket}:
    get:
      tags:
        - Matchings
      summary: get a waiting user by specified uuid
      parameters:
        - name: numberedTicket
          in: path
          description: uuid
          required: true
          schema:
            type: string
      responses:
        '200':
          description: waiting user
          content:
            application/json:
              schema: 
                type: object
                items:
                  $ref: '#/components/schemas/waitingUser'
                example:
                  numberedTicket: 550e8400e29b41d4a716446655440000
                  admissionTicket: a205cbb134ff412dc3212333448f1200
                  status: waiting
                  waitedBy: "2018-12-08T03:40:50"
  /battle_rooms/{admissionTicket}:
    get:
      tags:
        - Battle Room
      summary: get battle room information
      parameters:
        - name: admissionTicket
          in: path
          description: uuid
          required: true
          schema:
            type: string
      responses:
        '200':
          description: battle room information
          content:
            application/json:
              schema: 
                type: object
                items:
                  $ref: '#/components/schemas/battleRoom'
                example:
                  status: ready
        
components: 
  schemas: 
    waitingUser:
      $ref: '#/components/schemas/waitingUser'
      properties: 
        status: 
          type: string
          enum:
            - waiting
            - admission
            - exited
          required: true
        numberedTicket:
          type: string
          format: uuid4
          required: true
        waitedBy:
          type: string
          format: dateTime
          required: true
        admissionTicket:
          type: string
          format: uuid4
          required: false
    battleRoom:
      $ref: '#/components/schemas/battleRoom'
      properties: 
        status: 
          type: string
          enum:
            - ready
            - started
            - ended
          required: true
